// Mocks generated by Mockito 5.4.6 from annotations
// in ecopal/test/features/fish_scanner/services/frame_processor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:camera/src/camera_image.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageFormat_0 extends _i1.SmartFake implements _i2.ImageFormat {
  _FakeImageFormat_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CameraImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraImage extends _i1.Mock implements _i2.CameraImage {
  MockCameraImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImageFormat get format =>
      (super.noSuchMethod(
            Invocation.getter(#format),
            returnValue: _FakeImageFormat_0(this, Invocation.getter(#format)),
          )
          as _i2.ImageFormat);

  @override
  int get height =>
      (super.noSuchMethod(Invocation.getter(#height), returnValue: 0) as int);

  @override
  int get width =>
      (super.noSuchMethod(Invocation.getter(#width), returnValue: 0) as int);

  @override
  List<_i2.Plane> get planes =>
      (super.noSuchMethod(
            Invocation.getter(#planes),
            returnValue: <_i2.Plane>[],
          )
          as List<_i2.Plane>);
}
